### ISSUE TITLE
There is nothing named 'PictureResult'

### ISSUE THREAD

**Issue by YugoCode** [bolav/fuse-camerapanel#10]
On Fuse 0.25 I get on every mention of PictureResult:

`There is nothing named 'PictureResult' accessible in this scope. Are you missing a package reference?`

**Comment by patrikhermansson** [comment]
Anyone finding a solution to this?

**Comment by santi-pdp** [comment]
Same issue here, any clue?

**Comment by santi-pdp** [comment]
This happened to me because of the file CameraAndroid.uno. In my case it complaied because of a ` character in the end of line 13. Deleting that compiled. Perhaps this helps you guys.

**Comment by patrikhermansson** [comment]
Thanks! This solved it!
